title: "George Trifonov Blog"
description: "Work, Coding, and Life"
repository: gtrifonov/gtrifonov.github.io
exclude: ["CNAME", "MIT-LICENSE", "README.md"]
permalink: /:year/:month/:day/:slug/index.html
theme: minima
header_pages:
  - about.md
plugins:
  - "jekyll-sitemap"
  - "jekyll-github-metadata"
